version:                    2.1
orbs:
  aws-ecr:                  circleci/aws-ecr@6.11.0
  aws-ecs:                  circleci/aws-ecs@1.2.0

executors:
  docker_build:
    machine:
      docker_layer_caching: true

jobs:
  build:
    machine:
      image:                circleci/classic:edge
    steps:
      - checkout
      - run:
          name:             docker-compose build
          command:          docker-compose build

  test:
    machine:
      image:                circleci/classic:edge
    steps:
      - checkout
      - run:
          name:             docker-compose up -d
          command:          docker-compose up -d
      - run:                sleep 30
      - run:
          name:             docker-compose run back rails db:create RAILS_ENV=test
          command:          docker-compose run back rails db:create RAILS_ENV=test
      - run:
          name:             docker-compose run back rails db:migrate RAILS_ENV=test
          command:          docker-compose run back rails db:migrate RAILS_ENV=test
      - run:
          name:             docker-compose run back bundle exec rspec spec
          command:          docker-compose run back bundle exec rspec spec
      - run:
          name:             docker-compose down
          command:          docker-compose down

workflows:
    build_and_test:
      jobs:
      - build
      - test:
          requires:
            - build
      - aws-ecr/build_and_push_image:
            executor:       dockcer_build
            name:           'build-prod'
            account-url:    AWS_ECR_ACCOUNT_URL
            region:         AWS_REGION
            repo:           AWS_ECR_REPO_BACK
            tag:            "${CIRCLE_SHA1}"
            path:           ./back
            dockerfile:     Dockerfile.pro
