version:           2

jobs:
  build:
    machine:
      image:       circleci/classic:edge
    steps:
      - checkout
      - run:
          name:    docker-compose build
          command: docker-compose build
      - run:
          name:    docker-compose run back bundle install
          command: docker-compose run back bundle install
      - run:
          name:    docker-compose up -d
          command: docker-compose up -d
      - run:       sleep 30
      - run:
          name:    docker-compose run back rails db:create RAILS_ENV=test
          command: docker-compose run back rails db:create RAILS_ENV=test
      - run:
          name:    docker-compose run back rails db:migrate RAILS_ENV=test
          command: docker-compose run back rails db:migrate RAILS_ENV=test
      - run:
          name:    docker-compose run back bundle exec rspec spec
          command: docker-compose run back bundle exec rspec spec
      - run:
          name:    docker-compose down
          command: docker-compose down

# orbs:
#   aws-ecr:       circleci/aws-ecr@6.0.0
#   aws-ecs:       circleci/aws-ecs@1.2.0
#
# workflows:
#   build-and-deploy::
#     jobs:
#       - aws-ecr/build-and-push-image:
#           region: AWS_REGION
#           account-url: AWS_ECR_ACCOUNT_URL
#           repo:  '${MY_APP_PREFIX}-sample'
#           path:  '/back'
#           tag:   "${CIRCLE_SHA1}"
#
#       - aws-ecr/build-and-push-image:
#           account-url: AWS_ECR_ACCOUNT_URL
#           aws-access-key-id: AWS_ACCESS_KEY_ID
#           aws-secret-access-key: AWS_SECRET_ACCESS_KEY
#           create-repo: true
#           dockerfile: Dockerfile
#           path:  .
#           region: AWS_REGION
#           repo:  circleci-ecr-orb-demo
#           tag:   "$CIRCLE_SHA1"
#
#       - aws-ecs/deploy-service-update:
#           requires:
#             - aws-ecr/build-and-push-image
#           family: '${MY_APP_PREFIX}-task'
#           cluster-name: '${MY_APP_PREFIX}-cluster'
#           service-name: '${MY_APP_PREFIX}-service'
#           container-image-name-updates: 'container=${MY_APP_PREFIX}-container,tag=${CIRCLE_SHA1}'
